local M = {}

local function styled(highlight, style)
  return vim.tbl_extend("force", highlight, style or {})
end

function M.get(c, opts)
  local background = opts.transparent and c.none or c.bg
  local inactive_background = opts.transparent and c.none or (opts.dim_inactive and c.bg_dark or c.bg)

  return {
    -- Editor UI
    Normal = { fg = c.fg, bg = background },
    NormalNC = { fg = c.fg, bg = inactive_background },
    NormalFloat = { fg = c.fg_float, bg = c.bg_float },
    NormalSB = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    FloatBorder = { fg = c.border_highlight, bg = c.bg_float },
    FloatTitle = { fg = c.border_highlight, bg = c.bg_float, bold = true },
    ColorColumn = { bg = c.bg_dark },
    Conceal = { fg = c.fg_gutter },
    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = "Cursor",
    CursorIM = "Cursor",
    CursorColumn = { bg = c.bg_highlight },
    CursorLine = { bg = c.bg_highlight },
    Directory = { fg = c.blue },
    EndOfBuffer = { fg = background },
    ErrorMsg = { fg = c.error },
    WinSeparator = { fg = c.border, bold = true },
    VertSplit = "WinSeparator",
    Folded = { fg = c.blue, bg = c.bg_highlight },
    FoldColumn = { fg = c.comment, bg = background },
    SignColumn = { fg = c.fg_gutter, bg = background },
    SignColumnSB = { fg = c.fg_gutter, bg = c.bg_sidebar },
    Substitute = { fg = c.bg, bg = c.red },
    LineNr = { fg = c.fg_gutter },
    LineNrAbove = "LineNr",
    LineNrBelow = "LineNr",
    CursorLineNr = { fg = c.orange, bold = true },
    MatchParen = { fg = c.orange, bold = true },
    ModeMsg = { fg = c.fg_dark, bold = true },
    MsgArea = { fg = c.fg_dark },
    MoreMsg = { fg = c.blue },
    NonText = { fg = c.fg_gutter },
    Question = { fg = c.blue },
    QuickFixLine = { bg = c.bg_visual, bold = true },
    SpecialKey = { fg = c.fg_gutter },
    StatusLine = { fg = c.fg_sidebar, bg = c.bg_statusline },
    StatusLineNC = { fg = c.fg_gutter, bg = c.bg_statusline },
    TabLine = { fg = c.fg_gutter, bg = c.bg_statusline },
    TabLineFill = { bg = opts.transparent and c.none or c.black },
    TabLineSel = { fg = c.bg, bg = c.blue, bold = true },
    Title = { fg = c.blue, bold = true },
    Visual = { bg = c.bg_visual },
    VisualNOS = "Visual",
    WarningMsg = { fg = c.warning },
    OkMsg = { fg = c.green },
    Whitespace = { fg = c.fg_gutter },
    WildMenu = { bg = c.bg_visual },
    WinBar = "StatusLine",
    WinBarNC = "StatusLineNC",
    Added = { fg = c.git.add },
    Changed = { fg = c.git.change },
    Removed = { fg = c.git.delete },
    FloatShadow = { bg = c.palette.slate[1], blend = 50 },
    FloatShadowThrough = { bg = c.palette.slate[2], blend = 100 },
    NvimInternalError = { fg = c.error, bg = c.diagnostic_bg.error },
    RedrawDebugClear = { bg = c.palette.amber[3] },
    RedrawDebugComposed = { bg = c.palette.green[3] },
    RedrawDebugRecompose = { bg = c.palette.red[3] },

    -- Menus and search
    Pmenu = { fg = c.fg, bg = c.bg_popup },
    PmenuMatch = { fg = c.cyan, bg = c.bg_popup },
    PmenuSel = { fg = c.fg, bg = c.palette.blue[4] },
    PmenuMatchSel = { fg = c.cyan, bg = c.palette.blue[4], bold = true },
    PmenuSbar = { bg = c.palette.blue[3] },
    PmenuThumb = { bg = c.palette.blue[7] },
    Search = { fg = c.fg_search, bg = c.bg_search },
    IncSearch = { fg = c.palette.orange[1], bg = c.orange },
    CurSearch = "IncSearch",

    -- Diff and spelling
    DiffAdd = { bg = c.diff.add },
    DiffChange = { bg = c.diff.change },
    DiffDelete = { bg = c.diff.delete },
    DiffText = { bg = c.diff.text },
    SpellBad = { sp = c.error, undercurl = true },
    SpellCap = { sp = c.warning, undercurl = true },
    SpellLocal = { sp = c.info, undercurl = true },
    SpellRare = { sp = c.hint, undercurl = true },

    -- Vim syntax
    Bold = { fg = c.fg, bold = true },
    Italic = { fg = c.fg, italic = true },
    Comment = styled({ fg = c.comment }, opts.styles.comments),
    Constant = { fg = c.orange },
    String = { fg = c.green },
    Character = "String",
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Float = "Number",
    Identifier = styled({ fg = c.magenta }, opts.styles.variables),
    Function = styled({ fg = c.blue }, opts.styles.functions),
    Statement = { fg = c.magenta },
    Conditional = { fg = c.purple },
    Repeat = "Conditional",
    Label = { fg = c.blue },
    Operator = { fg = c.cyan },
    Keyword = styled({ fg = c.purple }, opts.styles.keywords),
    Exception = "Keyword",
    PreProc = { fg = c.cyan },
    Include = { fg = c.purple },
    Define = "PreProc",
    Macro = "PreProc",
    PreCondit = "PreProc",
    Type = { fg = c.cyan },
    StorageClass = "Type",
    Structure = "Type",
    Typedef = "Type",
    Special = { fg = c.teal },
    SpecialChar = { fg = c.magenta },
    Tag = "Special",
    Delimiter = { fg = c.fg_dark },
    SpecialComment = "Special",
    Debug = { fg = c.orange },
    Underlined = { fg = c.blue, underline = true },
    Ignore = { fg = c.fg_gutter },
    Error = { fg = c.error },
    Todo = { fg = c.palette.blue[1], bg = c.todo, bold = true },

    -- Native LSP and diagnostics
    LspReferenceText = { bg = c.palette.blue[3] },
    LspReferenceRead = { bg = c.palette.blue[3] },
    LspReferenceWrite = { bg = c.palette.blue[4] },
    LspSignatureActiveParameter = { bg = c.bg_visual, bold = true },
    LspCodeLens = { fg = c.comment },
    LspCodeLensSeparator = { fg = c.fg_gutter },
    LspInlayHint = { fg = c.palette.slate[9], bg = c.palette.blue[2] },
    LspInfoBorder = "FloatBorder",
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnnecessary = { fg = c.fg_gutter },
    DiagnosticDeprecated = { strikethrough = true },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.diagnostic_bg.error },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.diagnostic_bg.warning },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.diagnostic_bg.info },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.diagnostic_bg.hint },
    DiagnosticVirtualTextOk = { fg = c.green, bg = c.palette.green[2] },
    DiagnosticUnderlineError = { sp = c.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.warning, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.hint, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.green, undercurl = true },

    -- Legacy and filetype groups
    healthError = "DiagnosticError",
    healthSuccess = "DiagnosticOk",
    healthWarning = "DiagnosticWarn",
    diffAdded = { fg = c.git.add, bg = c.diff.add },
    diffRemoved = { fg = c.git.delete, bg = c.diff.delete },
    diffChanged = { fg = c.git.change, bg = c.diff.change },
    diffOldFile = { fg = c.red },
    diffNewFile = { fg = c.green },
    diffFile = { fg = c.blue },
    diffLine = { fg = c.comment },
    diffIndexLine = { fg = c.magenta },
    helpCommand = { fg = c.blue, bg = c.bg_highlight },
    helpExample = { fg = c.comment },
    htmlH1 = { fg = c.magenta, bold = true },
    htmlH2 = { fg = c.blue, bold = true },
    qfFileName = { fg = c.blue },
    qfLineNr = { fg = c.fg_gutter },
  }
end

return M
