local M = {}

function M.get(c)
  local groups = {
    -- Completion menus (nvim-cmp and blink.cmp)
    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.fg_gutter, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.blue, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.blue },
    CmpItemMenu = { fg = c.comment },
    CmpItemKindDefault = { fg = c.fg_dark },
    BlinkCmpLabel = "CmpItemAbbr",
    BlinkCmpLabelDeprecated = "CmpItemAbbrDeprecated",
    BlinkCmpLabelMatch = "CmpItemAbbrMatch",
    BlinkCmpKind = "CmpItemKindDefault",
    BlinkCmpMenu = "Pmenu",
    BlinkCmpMenuBorder = "FloatBorder",
    BlinkCmpMenuSelection = "PmenuSel",
    BlinkCmpDoc = "NormalFloat",
    BlinkCmpDocBorder = "FloatBorder",
    BlinkCmpSignatureHelp = "NormalFloat",
    BlinkCmpSignatureHelpBorder = "FloatBorder",

    -- Telescope and fzf-lua
    TelescopeNormal = { fg = c.fg, bg = c.bg_float },
    TelescopeBorder = { fg = c.border_highlight, bg = c.bg_float },
    TelescopeTitle = { fg = c.blue, bold = true },
    TelescopePromptNormal = { fg = c.fg, bg = c.bg_highlight },
    TelescopePromptBorder = { fg = c.border_highlight, bg = c.bg_highlight },
    TelescopePromptTitle = { fg = c.blue, bg = c.bg_highlight, bold = true },
    TelescopePreviewTitle = { fg = c.blue, bg = c.bg_float, bold = true },
    TelescopeResultsTitle = { fg = c.blue, bg = c.bg_float, bold = true },
    TelescopeSelection = { bg = c.bg_visual, bold = true },
    TelescopeSelectionCaret = { fg = c.blue },
    TelescopeMatching = { fg = c.blue, bold = true },
    FzfLuaNormal = "TelescopeNormal",
    FzfLuaBorder = "TelescopeBorder",
    FzfLuaTitle = "TelescopeTitle",
    FzfLuaCursorLine = "TelescopeSelection",
    FzfLuaSearch = "TelescopeMatching",

    -- Git
    GitSignsAdd = { fg = c.git.add },
    GitSignsChange = { fg = c.git.change },
    GitSignsDelete = { fg = c.git.delete },
    GitSignsCurrentLineBlame = { fg = c.comment, italic = true },
    GitSignsStagedAdd = { fg = c.git.staged_add },
    GitSignsStagedAddCul = "GitSignsStagedAdd",
    GitSignsStagedAddNr = "GitSignsStagedAdd",
    GitSignsStagedUntracked = "GitSignsStagedAdd",
    GitSignsStagedUntrackedCul = "GitSignsStagedAdd",
    GitSignsStagedUntrackedNr = "GitSignsStagedAdd",
    GitSignsStagedChange = { fg = c.git.staged_change },
    GitSignsStagedChangeCul = "GitSignsStagedChange",
    GitSignsStagedChangeNr = "GitSignsStagedChange",
    GitSignsStagedChangedelete = "GitSignsStagedChange",
    GitSignsStagedChangedeleteCul = "GitSignsStagedChange",
    GitSignsStagedChangedeleteNr = "GitSignsStagedChange",
    GitSignsStagedDelete = { fg = c.git.staged_delete },
    GitSignsStagedDeleteCul = "GitSignsStagedDelete",
    GitSignsStagedDeleteNr = "GitSignsStagedDelete",
    GitSignsStagedTopdelete = "GitSignsStagedDelete",
    GitSignsStagedTopdeleteCul = "GitSignsStagedDelete",
    GitSignsStagedTopdeleteNr = "GitSignsStagedDelete",
    GitGutterAdd = "GitSignsAdd",
    GitGutterChange = "GitSignsChange",
    GitGutterDelete = "GitSignsDelete",
    NeogitDiffAdd = "DiffAdd",
    NeogitDiffDelete = "DiffDelete",
    NeogitDiffContext = { fg = c.fg_dark },
    NeogitHunkHeader = { fg = c.fg_dark, bg = c.bg_highlight },
    NeogitHunkHeaderHighlight = { fg = c.blue, bg = c.palette.blue[4], bold = true },

    -- File explorers
    NeoTreeNormal = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NeoTreeNormalNC = "NeoTreeNormal",
    NeoTreeEndOfBuffer = { fg = c.bg_sidebar, bg = c.bg_sidebar },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeDirectoryIcon = { fg = c.blue },
    NeoTreeRootName = { fg = c.blue, bold = true },
    NeoTreeFileNameOpened = { fg = c.blue },
    NeoTreeGitAdded = { fg = c.git.add },
    NeoTreeGitModified = { fg = c.git.change },
    NeoTreeGitDeleted = { fg = c.git.delete },
    NeoTreeGitIgnored = { fg = c.git.ignore },
    NeoTreeIndentMarker = { fg = c.fg_gutter },
    NeoTreeWinSeparator = { fg = c.border, bg = c.bg_sidebar },
    NvimTreeNormal = "NeoTreeNormal",
    NvimTreeNormalNC = "NeoTreeNormalNC",
    NvimTreeEndOfBuffer = "NeoTreeEndOfBuffer",
    NvimTreeFolderName = "NeoTreeDirectoryName",
    NvimTreeFolderIcon = "NeoTreeDirectoryIcon",
    NvimTreeOpenedFolderName = { fg = c.blue },
    NvimTreeRootFolder = "NeoTreeRootName",
    NvimTreeGitNew = "NeoTreeGitAdded",
    NvimTreeGitDirty = "NeoTreeGitModified",
    NvimTreeGitDeleted = "NeoTreeGitDeleted",
    NvimTreeIndentMarker = "NeoTreeIndentMarker",
    NvimTreeWinSeparator = "NeoTreeWinSeparator",

    -- Navigation and UI
    WhichKey = { fg = c.blue },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.fg_gutter },
    WhichKeyFloat = "NormalFloat",
    BufferLineFill = { bg = c.bg_dark },
    BufferLineBackground = { fg = c.fg_gutter, bg = c.bg_statusline },
    BufferLineBufferSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineBufferVisible = { fg = c.fg_dark, bg = c.bg_statusline },
    BufferLineIndicatorSelected = { fg = c.blue, bg = c.bg },
    BufferLineModified = { fg = c.orange, bg = c.bg_statusline },
    BufferLineModifiedSelected = { fg = c.orange, bg = c.bg },
    IblIndent = { fg = c.palette.slate[5] },
    IblScope = { fg = c.palette.slate[7] },
    IndentBlanklineChar = "IblIndent",
    IndentBlanklineContextChar = "IblScope",
    TreesitterContext = { bg = c.bg_dark },
    TreesitterContextLineNumber = { fg = c.blue, bg = c.bg_dark },
    IlluminatedWordText = { bg = c.bg_highlight },
    IlluminatedWordRead = "IlluminatedWordText",
    IlluminatedWordWrite = "IlluminatedWordText",

    -- Plugin managers and diagnostics
    LazyNormal = { fg = c.fg, bg = c.bg_float },
    LazyButton = { fg = c.fg_dark, bg = c.bg_highlight },
    LazyButtonActive = { fg = c.blue, bg = c.bg_highlight, bold = true },
    LazyH1 = { fg = c.blue, bg = c.bg_highlight, bold = true },
    LazySpecial = { fg = c.blue },
    MasonNormal = "NormalFloat",
    MasonHeader = { fg = c.blue, bg = c.bg_highlight, bold = true },
    MasonHighlight = { fg = c.blue },
    MasonHighlightBlock = { fg = c.blue, bg = c.bg_highlight },
    TroubleNormal = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    TroubleNormalNC = "TroubleNormal",
    TroubleCount = { fg = c.blue, bg = c.bg_highlight },
    TroubleText = { fg = c.fg_dark },
    TroubleIndent = { fg = c.fg_gutter },

    -- Notifications and dashboards
    NoiceCmdlinePopup = "NormalFloat",
    NoiceCmdlinePopupBorder = "FloatBorder",
    NoiceCmdlineIcon = { fg = c.blue },
    NoiceConfirm = "NormalFloat",
    NotifyERRORBorder = { fg = c.palette.red[8] },
    NotifyWARNBorder = { fg = c.palette.amber[8] },
    NotifyINFOBorder = { fg = c.palette.blue[8] },
    NotifyDEBUGBorder = { fg = c.palette.slate[8] },
    NotifyTRACEBorder = { fg = c.palette.purple[8] },
    NotifyERRORIcon = "DiagnosticError",
    NotifyWARNIcon = "DiagnosticWarn",
    NotifyINFOIcon = "DiagnosticInfo",
    NotifyDEBUGIcon = { fg = c.comment },
    NotifyTRACEIcon = { fg = c.purple },
    NotifyERRORTitle = "DiagnosticError",
    NotifyWARNTitle = "DiagnosticWarn",
    NotifyINFOTitle = "DiagnosticInfo",
    DashboardHeader = { fg = c.blue },
    DashboardCenter = { fg = c.fg },
    DashboardFooter = { fg = c.comment, italic = true },
    AlphaHeader = "DashboardHeader",
    AlphaButtons = "DashboardCenter",
    AlphaFooter = "DashboardFooter",

    -- Debugging and tests
    DapBreakpoint = { fg = c.red },
    DapBreakpointCondition = { fg = c.yellow },
    DapStopped = { fg = c.green, bg = c.palette.green[2] },
    DapLogPoint = { fg = c.blue },
    DapUIVariable = { fg = c.fg },
    DapUIValue = { fg = c.fg },
    DapUIScope = { fg = c.blue },
    DapUIType = { fg = c.fg_dark },
    DapUIThread = { fg = c.green },
    NeotestPassed = { fg = c.green },
    NeotestFailed = { fg = c.red },
    NeotestRunning = { fg = c.yellow },
    NeotestSkipped = { fg = c.comment },
    NeotestFile = { fg = c.blue },
    NeotestDir = { fg = c.blue },
    NeotestNamespace = { fg = c.fg },
    NeotestAdapterName = { fg = c.blue, bold = true },

    -- Motion, breadcrumbs, and modern UI plugins
    FlashLabel = { fg = c.palette.red[1], bg = c.red, bold = true },
    FlashMatch = { fg = c.cyan, bold = true },
    FlashCurrent = { fg = c.palette.blue[1], bg = c.blue, bold = true },
    HopNextKey = { fg = c.magenta, bold = true },
    HopNextKey1 = { fg = c.cyan, bold = true },
    HopNextKey2 = { fg = c.blue },
    LeapMatch = "FlashMatch",
    LeapLabelPrimary = "FlashLabel",
    LeapLabelSecondary = "FlashCurrent",
    NavicIconsFile = { fg = c.blue },
    NavicText = { fg = c.fg_dark },
    NavicSeparator = { fg = c.fg_gutter },
    AerialLine = { bg = c.bg_highlight },
    AerialGuide = { fg = c.fg_gutter },
    ScrollbarHandle = { bg = c.palette.slate[6] },
    ScrollbarSearch = { fg = c.yellow },
    ScrollbarError = { fg = c.error },
    ScrollbarWarn = { fg = c.warning },
    ScrollbarInfo = { fg = c.info },
    ScrollbarHint = { fg = c.hint },

    -- Markdown and snacks.nvim
    RenderMarkdownCode = { bg = c.bg_dark },
    RenderMarkdownCodeInline = { fg = c.blue, bg = c.bg_highlight },
    RenderMarkdownBullet = { fg = c.cyan },
    RenderMarkdownDash = { fg = c.fg_gutter },
    RenderMarkdownQuote = { fg = c.comment },
    RenderMarkdownLink = { fg = c.teal },
    SnacksPickerMatch = { fg = c.blue, bold = true },
    SnacksPickerSelected = { bg = c.bg_visual },
    SnacksPickerInputNormalFloat = { fg = c.fg, bg = c.bg_highlight },
    SnacksPickerInputBorder = { fg = c.border_highlight, bg = c.bg_highlight },
    SnacksPickerInputTitle = { fg = c.blue, bg = c.bg_highlight, bold = true },
    SnacksPickerListNormalFloat = { fg = c.fg, bg = c.bg_float },
    SnacksPickerPreviewNormalFloat = { fg = c.fg, bg = c.bg_float },
    SnacksPickerBoxNormalFloat = { fg = c.fg, bg = c.bg_float },
    SnacksPickerBorder = "FloatBorder",
    SnacksBackdrop = { bg = c.bg_dark },
    SnacksDashboardHeader = "DashboardHeader",
    SnacksDashboardDesc = { fg = c.fg },
    SnacksDashboardKey = { fg = c.blue },
    SnacksDashboardFooter = "DashboardFooter",
    MiniCursorword = { bg = c.bg_highlight },
    MiniCursorwordCurrent = "MiniCursorword",
    MiniIndentscopeSymbol = { fg = c.blue },
    MiniJump = { fg = c.palette.red[1], bg = c.red },
    MiniStatuslineModeNormal = { fg = c.blue, bg = c.bg_highlight, bold = true },
    MiniStatuslineModeInsert = { fg = c.blue, bg = c.bg_highlight, bold = true },
    MiniStatuslineModeVisual = { fg = c.blue, bg = c.bg_highlight, bold = true },
    MiniStatuslineModeReplace = { fg = c.blue, bg = c.bg_highlight, bold = true },
    MiniStatuslineModeCommand = { fg = c.blue, bg = c.bg_highlight, bold = true },

    -- todo-comments.nvim
    TodoBgFIX = { fg = c.palette.red[1], bg = c.red, bold = true },
    TodoBgHACK = { fg = c.palette.amber[1], bg = c.yellow, bold = true },
    TodoBgWARN = { fg = c.palette.amber[1], bg = c.yellow, bold = true },
    TodoBgPERF = { fg = c.palette.purple[1], bg = c.purple, bold = true },
    TodoBgNOTE = { fg = c.palette.blue[1], bg = c.blue, bold = true },
    TodoBgTODO = { fg = c.palette.blue[1], bg = c.blue, bold = true },
    TodoBgTEST = { fg = c.palette.teal[1], bg = c.teal, bold = true },
    TodoFgFIX = { fg = c.red },
    TodoFgHACK = { fg = c.yellow },
    TodoFgWARN = { fg = c.yellow },
    TodoFgPERF = { fg = c.purple },
    TodoFgNOTE = { fg = c.blue },
    TodoFgTODO = { fg = c.blue },
    TodoFgTEST = { fg = c.teal },
    TodoSignFIX = "TodoFgFIX",
    TodoSignHACK = "TodoFgHACK",
    TodoSignWARN = "TodoFgWARN",
    TodoSignPERF = "TodoFgPERF",
    TodoSignNOTE = "TodoFgNOTE",
    TodoSignTODO = "TodoFgTODO",
    TodoSignTEST = "TodoFgTEST",
  }

  local kinds = {
    "Array",
    "Boolean",
    "Class",
    "Color",
    "Constant",
    "Constructor",
    "Copilot",
    "Enum",
    "EnumMember",
    "Event",
    "Field",
    "File",
    "Folder",
    "Function",
    "Interface",
    "Key",
    "Keyword",
    "Method",
    "Module",
    "Namespace",
    "Null",
    "Number",
    "Object",
    "Operator",
    "Package",
    "Property",
    "Reference",
    "Snippet",
    "String",
    "Struct",
    "Text",
    "TypeParameter",
    "Unit",
    "Value",
    "Variable",
  }

  for _, kind in ipairs(kinds) do
    groups["CmpItemKind" .. kind] = { fg = c.fg_dark }
    groups["BlinkCmpKind" .. kind] = { fg = c.fg_dark }
    groups["NavicIcons" .. kind] = { fg = c.fg_gutter }
    groups["Aerial" .. kind .. "Icon"] = { fg = c.fg_dark }
  end

  return groups
end

return M
