local M = {}

local function styled(highlight, style)
  return vim.tbl_extend("force", highlight, style or {})
end

function M.get(c, opts)
  return {
    ["@none"] = {},
    ["@comment"] = "Comment",
    ["@comment.error"] = { fg = c.error },
    ["@comment.warning"] = { fg = c.warning },
    ["@comment.todo"] = { fg = c.todo },
    ["@comment.note"] = { fg = c.hint },
    ["@comment.info"] = { fg = c.info },
    ["@comment.hint"] = { fg = c.hint },
    ["@constant"] = "Constant",
    ["@constant.builtin"] = "Special",
    ["@constant.macro"] = "Define",
    ["@string"] = "String",
    ["@string.documentation"] = { fg = c.yellow },
    ["@string.regexp"] = { fg = c.cyan },
    ["@string.escape"] = { fg = c.magenta },
    ["@string.special"] = "SpecialChar",
    ["@string.special.symbol"] = { fg = c.violet },
    ["@string.special.url"] = "Underlined",
    ["@character"] = "Character",
    ["@character.special"] = "SpecialChar",
    ["@boolean"] = "Boolean",
    ["@number"] = "Number",
    ["@number.float"] = "Float",

    ["@function"] = "Function",
    ["@function.builtin"] = "Special",
    ["@function.call"] = "@function",
    ["@function.macro"] = "Macro",
    ["@function.method"] = "Function",
    ["@function.method.call"] = "@function.method",
    ["@constructor"] = { fg = c.magenta },
    ["@constructor.tsx"] = { fg = c.cyan },
    ["@variable"] = styled({ fg = c.fg }, opts.styles.variables),
    ["@variable.builtin"] = { fg = c.red },
    ["@variable.parameter"] = { fg = c.yellow },
    ["@variable.parameter.builtin"] = { fg = c.orange },
    ["@variable.member"] = { fg = c.teal },
    ["@property"] = { fg = c.teal },

    ["@keyword"] = styled({ fg = c.purple }, opts.styles.keywords),
    ["@keyword.coroutine"] = "@keyword",
    ["@keyword.function"] = styled({ fg = c.magenta }, opts.styles.functions),
    ["@keyword.operator"] = "@operator",
    ["@keyword.import"] = "Include",
    ["@keyword.storage"] = "StorageClass",
    ["@keyword.repeat"] = "Repeat",
    ["@keyword.return"] = "@keyword",
    ["@keyword.debug"] = "Debug",
    ["@keyword.exception"] = "Exception",
    ["@keyword.conditional"] = "Conditional",
    ["@keyword.directive"] = "PreProc",
    ["@keyword.directive.define"] = "Define",
    ["@operator"] = { fg = c.cyan },

    ["@type"] = "Type",
    ["@type.builtin"] = { fg = c.cyan },
    ["@type.definition"] = "Typedef",
    ["@type.qualifier"] = "@keyword",
    ["@attribute"] = "PreProc",
    ["@annotation"] = "PreProc",
    ["@module"] = "Include",
    ["@module.builtin"] = { fg = c.red },
    ["@namespace"] = "@module",
    ["@namespace.builtin"] = "@variable.builtin",
    ["@label"] = "Label",

    ["@punctuation.delimiter"] = { fg = c.cyan },
    ["@punctuation.bracket"] = { fg = c.fg_dark },
    ["@punctuation.special"] = { fg = c.magenta },
    ["@tag"] = { fg = c.red },
    ["@tag.builtin"] = "@tag",
    ["@tag.attribute"] = "@property",
    ["@tag.delimiter"] = "Delimiter",

    ["@markup"] = "@none",
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = "Title",
    ["@markup.heading.1.markdown"] = { fg = c.blue, bg = c.palette.blue[2], bold = true },
    ["@markup.heading.2.markdown"] = { fg = c.yellow, bg = c.palette.amber[2], bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.green, bg = c.palette.green[2], bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.teal, bg = c.palette.teal[2], bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.magenta, bg = c.palette.pink[2], bold = true },
    ["@markup.heading.6.markdown"] = { fg = c.purple, bg = c.palette.purple[2], bold = true },
    ["@markup.quote"] = { fg = c.comment, italic = true },
    ["@markup.math"] = "Special",
    ["@markup.link"] = { fg = c.teal },
    ["@markup.link.label"] = "SpecialChar",
    ["@markup.link.url"] = "Underlined",
    ["@markup.raw"] = "String",
    ["@markup.raw.block"] = { bg = c.bg_dark },
    ["@markup.raw.markdown_inline"] = { fg = c.blue, bg = c.bg_highlight },
    ["@markup.list"] = { fg = c.cyan },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.blue },

    ["@diff.plus"] = "DiffAdd",
    ["@diff.minus"] = "DiffDelete",
    ["@diff.delta"] = "DiffChange",

    -- Compatibility aliases used by older nvim-treesitter queries.
    ["@parameter"] = "@variable.parameter",
    ["@field"] = "@variable.member",
    ["@method"] = "@function.method",
    ["@method.call"] = "@function.method.call",
    ["@conditional"] = "@keyword.conditional",
    ["@repeat"] = "@keyword.repeat",
    ["@exception"] = "@keyword.exception",
    ["@include"] = "@keyword.import",
    ["@text"] = "@markup",
    ["@text.strong"] = "@markup.strong",
    ["@text.emphasis"] = "@markup.italic",
    ["@text.underline"] = "@markup.underline",
    ["@text.strike"] = "@markup.strikethrough",
    ["@text.title"] = "@markup.heading",
    ["@text.literal"] = "@markup.raw",
    ["@text.uri"] = "@markup.link.url",
    ["@text.reference"] = "@markup.link",
    ["@text.todo"] = "@comment.todo",
    ["@text.note"] = "@comment.note",
    ["@text.warning"] = "@comment.warning",
    ["@text.danger"] = "@comment.error",
  }
end

return M
